### ISSUE TITLE
Error in molecule/default/playbook.yml

### ISSUE THREAD

**Issue by bbaassssiiee** [infothrill/molecule-bugreport#1]
You mention the role **bugreport**, should be **molecule-bugreport**

```
---
- name: Converge
  hosts: all
  roles:
    - role: molecule-bugreport
```
